package cli

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// Codegen writes a TypeScript module with typed wrappers for integration
// endpoints. It is an optional layer over hex.integrations.call: the module
// imports nothing and takes anything with that call method, so apps can mix
// typed and untyped calls and keep their own client version.

// catalogIntegration is one entry of GET /api/hex/integrations.
type catalogIntegration struct {
	Name             string            `json:"name"`
	Title            string            `json:"title"`
	Description      string            `json:"description"`
	RequiresApproval bool              `json:"requiresApproval"`
	Connector        string            `json:"connector"`
	Endpoints        []catalogEndpoint `json:"endpoints"`
}

type catalogEndpoint struct {
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	Permission   string          `json:"permission"`
	Write        bool            `json:"write"`
	InputSchema  json.RawMessage `json:"inputSchema"`
	OutputSchema json.RawMessage `json:"outputSchema"`
}

const generatedHeader = `// Generated by ` + "`hex integrations codegen`" + `. Do not edit: run the command
// again when the platform's integrations change.
//
// Usage:
//   import { typedIntegrations } from "./hex-integrations";
//   const integrations = typedIntegrations(hex.integrations);
//   const result = await integrations.slack.users({ limit: 50 });
//
// hex.integrations.call(...) keeps working alongside these wrappers. Exclude
// this file from formatters (for example in .prettierignore) so that
// hex integrations codegen --check can compare it.

/** Anything that calls integration endpoints, such as hex.integrations. */
export interface IntegrationCaller {
  call<T>(integration: string, endpoint: string, input?: unknown): Promise<T>;
}
`

func (a *App) integrationCodegenCommand(options *siteCommandOptions) *cobra.Command {
	var output, catalogFile string
	var only []string
	var check bool
	command := &cobra.Command{
		Use:   "codegen",
		Short: "Generate typed TypeScript wrappers for integration endpoints",
		Long: "Generate a TypeScript module with input and output types and typed wrappers for the platform's integration endpoints.\n" +
			"The module is optional: hex.integrations.call keeps working. Use --only to limit it to the endpoints an app uses,\n" +
			"--catalog to generate from a saved `hex integrations catalog` instead of the platform, and --check in CI.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if check && output == "" {
				return errors.New("--check needs --out, the generated file to compare")
			}
			catalog, err := a.codegenCatalog(cmd, options, catalogFile)
			if err != nil {
				return err
			}
			generated, err := generateIntegrationModule(catalog, only)
			if err != nil {
				return err
			}
			if output == "" {
				_, err := a.Out.Write(generated)
				return err
			}

			path := resolvePath(a.Dir, output)
			if check {
				existing, err := os.ReadFile(path)
				if err != nil || !bytes.Equal(existing, generated) {
					return fmt.Errorf("%s is out of date; run hex integrations codegen --out %s", output, output)
				}
				fmt.Fprintf(a.Out, "%s is up to date\n", output)
				return nil
			}
			if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
				return err
			}
			if err := atomicWrite(path, generated, 0644); err != nil {
				return fmt.Errorf("write %s: %w", output, err)
			}
			fmt.Fprintf(a.Out, "Wrote %s\n", output)
			return nil
		},
	}
	flags := command.Flags()
	flags.StringVar(&output, "out", "", "File to write, such as src/hex-integrations.ts (default: standard output)")
	flags.StringSliceVar(&only, "only", nil, "Endpoints to include, such as hubspot.*,slack.users (default: all)")
	flags.StringVar(&catalogFile, "catalog", "", "Generate from a saved catalog JSON file instead of the platform")
	flags.BoolVar(&check, "check", false, "Fail if --out differs from what would be generated")
	return command
}

func (a *App) codegenCatalog(cmd *cobra.Command, options *siteCommandOptions, catalogFile string) ([]catalogIntegration, error) {
	var data []byte
	if catalogFile != "" {
		contents, err := os.ReadFile(resolvePath(a.Dir, catalogFile))
		if err != nil {
			return nil, fmt.Errorf("read catalog: %w", err)
		}
		data = contents
	} else {
		project, err := a.commandConfig(options.platform, false)
		if err != nil {
			return nil, err
		}
		response, err := a.apiRequest(cmd.Context(), project, "/api/hex/integrations")
		if err != nil {
			return nil, err
		}
		data = response
	}
	var catalog []catalogIntegration
	if err := json.Unmarshal(data, &catalog); err != nil {
		return nil, fmt.Errorf("invalid integration catalog: %w", err)
	}
	return catalog, nil
}

// generateIntegrationModule renders the module. Output depends only on the
// catalog and filter, so --check can compare it byte for byte.
func generateIntegrationModule(catalog []catalogIntegration, only []string) ([]byte, error) {
	for _, pattern := range only {
		if !validEndpointPattern(pattern) {
			return nil, fmt.Errorf("invalid --only pattern %q; use names such as hubspot.deals or hubspot.*", pattern)
		}
	}

	types := newTypeScriptTypes()
	var wrappers strings.Builder
	included := 0
	for _, integration := range catalog {
		var methods strings.Builder
		for _, endpoint := range integration.Endpoints {
			qualified := integration.Name + "." + endpoint.Name
			if len(only) > 0 && !matchesEndpointPattern(only, qualified) {
				continue
			}
			method, err := endpointWrapper(types, integration, endpoint)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", qualified, err)
			}
			methods.WriteString(method)
			included++
		}
		if methods.Len() == 0 {
			continue
		}
		wrappers.WriteString(docComment(integrationSummary(integration), 2))
		wrappers.WriteString("    " + propertyName(camelCase(integration.Name)) + ": {\n")
		wrappers.WriteString(methods.String())
		wrappers.WriteString("    },\n")
	}
	if included == 0 {
		return nil, errors.New("no integration endpoints match; check --only or the platform's integrations")
	}

	var module strings.Builder
	module.WriteString(generatedHeader)
	for _, declaration := range types.declarations {
		module.WriteString("\n" + declaration)
	}
	module.WriteString("\n/** Typed wrappers for the platform's integration endpoints. */\n")
	module.WriteString("export function typedIntegrations(integrations: IntegrationCaller) {\n")
	module.WriteString("  return {\n")
	module.WriteString(wrappers.String())
	module.WriteString("  };\n}\n")
	return []byte(module.String()), nil
}

func endpointWrapper(types *typeScriptTypes, integration catalogIntegration, endpoint catalogEndpoint) (string, error) {
	if len(endpoint.InputSchema) == 0 || len(endpoint.OutputSchema) == 0 {
		return "", errors.New("the platform did not provide both schemas; upgrade the platform")
	}
	base := pascalCase(integration.Name) + pascalCase(endpoint.Name)
	optionalInput, err := types.declare(base+"Input", "Input of "+integration.Name+"."+endpoint.Name+".", endpoint.InputSchema)
	if err != nil {
		return "", err
	}
	if _, err := types.declare(base+"Output", "Result of "+integration.Name+"."+endpoint.Name+".", endpoint.OutputSchema); err != nil {
		return "", err
	}

	parameter := "input: " + base + "Input"
	if optionalInput {
		parameter += " = {}"
	}
	var builder strings.Builder
	builder.WriteString(docComment(endpointSummary(endpoint), 3))
	builder.WriteString(fmt.Sprintf("      %s: (%s) =>\n", propertyName(camelCase(endpoint.Name)), parameter))
	builder.WriteString(fmt.Sprintf("        integrations.call<%sOutput>(%q, %q, input),\n", base, integration.Name, endpoint.Name))
	return builder.String(), nil
}

func integrationSummary(integration catalogIntegration) string {
	lines := []string{integration.Title}
	if integration.Description != "" {
		lines = append(lines, "", integration.Description)
	}
	if integration.Connector != "" {
		lines = append(lines, "", "Calls with the viewer's own connected "+integration.Connector+" account.")
	}
	if integration.RequiresApproval {
		lines = append(lines, "", "Needs a platform admin to approve each site.")
	}
	return strings.Join(lines, "\n")
}

func endpointSummary(endpoint catalogEndpoint) string {
	summary := endpoint.Description + "\n\nPermission: " + endpoint.Permission
	if endpoint.Write {
		summary += " (changes data; needs the site's editor role)"
	}
	return summary
}

func validEndpointPattern(pattern string) bool {
	if pattern == "*" {
		return true
	}
	integration, endpoint, found := strings.Cut(pattern, ".")
	return found && integration != "" && endpoint != "" && !strings.ContainsAny(integration, "*") &&
		(endpoint == "*" || !strings.Contains(endpoint, "*"))
}

func matchesEndpointPattern(patterns []string, name string) bool {
	for _, pattern := range patterns {
		if pattern == "*" || pattern == name {
			return true
		}
		if prefix, wildcard := strings.CutSuffix(pattern, "*"); wildcard && strings.HasPrefix(name, prefix) {
			return true
		}
	}
	return false
}
